### ISSUE TITLE
Serve optimized cloudinary images to save data costs

### ISSUE THREAD

**Issue by Jasonvdb** [big-neon/bn-ios#24]
bn-api currently returns `promo_image_url` which is the original uploaded image that can sometimes be around 4mb.

Because we're using cloudinary at the moment we can request a much smaller version which still looks fine on mobile.

bn-web has this helper function you can look at maybe translating to swift which does the URL manipulation:
https://github.com/big-neon/bn-web/blob/master/src/helpers/optimizedImageUrl.js

**Comment by Krakaw** [comment]
Closed by #22
