### ISSUE TITLE
Door person is intermittently unable to scan a ticket

### ISSUE THREAD

**Issue by Anziskavds** [big-neon/bn-ios#85]
Steps to reproduce:

- Door person is unable to scan a ticket, the screen brightness dims and it doesn't scan the ticket
- The screen stays dimmed after the door person scanned the ticket until the "X" has been clicked to exit the screen.
- The ticket only scans after the page has been refreshed
- This issue was found on Manual Mode

**Comment by Tas4tari** [comment]
Completed and closed
