### ISSUE TITLE
Doorperson - Guestlist check-in swipe to check-in "Sticky" reported on ipod touch

### ISSUE THREAD

**Issue by Tas4tari** [big-neon/bn-ios#99]
Description: 
Reports of the swipe to check-in being "Sticky" on a new ipod touch (same screen size as the iphone 5s I believe) 
Please investigate\r\n\r\n## 
Platform/Device/Browser Information:
Found on iOS iPhone 7+
found on OSX High Sierra Chrome version 37.1
Platform: iOS Device: new ipod touch

**Comment by mhlangagc** [comment]
Is this on the the native app or the react native app? @Tas4tari
